geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from mainapp.views import index, products

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from .views import products

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
]

users/urls.py
from django.urls import path
from .views import login, register, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
]

mainapp/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} | {self.category.name}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', blank=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm

from users.models import User


class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        field = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите логин'
        self.fields['username'].widget.attrs['placeholder'] = 'Введите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

mainapp/views.py
from django.shortcuts import render
from .models import ProductCategory, Product

def index(request):
    context = {
        'title': 'Main page',
        'name': 'GeekShop Store',
        'description': 'Новые образы и лучшие бренды на GeekShop Store.Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.'
    }
    return render(request, 'mainapp/index.html', context)


def products(request):
    products_data = Product.objects.all()
    categories_data = ProductCategory.objects.all()
    context = {
        'title': 'Main page',
        'name': 'GeekShop Store',
        'categories': categories_data,
        'slides': [
            {'img': 'vendor/img/slides/slide-1.jpg', 'pic_alt': 'First slide'},
            {'img': 'vendor/img/slides/slide-2.jpg', 'pic_alt': 'Second slide'},
            {'img': 'vendor/img/slides/slide-3.jpg', 'pic_alt': 'Third slide'},
        ],
        'products': products_data
    }

    return render(request, 'mainapp/products.html', context)

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse

# Create your views here.
from users.forms import UserLoginForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user.is_active:
                auth.login(request,user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()

    context = {
            'title': 'Authorization',
            'form': form
    }

    return render(request, 'users/login.html', context)


def register(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserLoginForm()
    context = {
        'title': 'Authorization',
        'form': form
    }
    return render(request, 'users/register.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title| title }}</title>



    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block custom_css %}
    {% endblock %}


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог
                        <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти
                            <i class="fas fa-sign-in-alt"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ user }}">User
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="admin/admin.html">
                            <i class="fas fa-users-cog"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти
                            <i class="fas fa-sign-out-alt"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block page_content%}
{% endblock %}


<!-- Footer -->
{% block page_footer %}
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html'%}
{% load static %}

{% block custom_css%}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block page_content %}
<!-- Page Content -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">{{ name }}</h1>
                <p>
                    {{ description }}
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="products.html">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block custom_css%}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}


{% block page_content%}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">{{ name }}</h1>
            <p>{% now "N j, Y, P" %}</p>
            <div class="list-group">
                {% for category in categories%}
                    <a href="#" class="list-group-item">{{ category.name }}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox" id="slides">
                    {% for slide in slides %}
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static slide.img %}" alt="{{ slide.pic_alt}}">
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }} RUB</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
{% endblock %}



{% block page_footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
    </div>
</footer>
{% endblock %}

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title|title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            <strong>Holy guacamole!</strong> You should check in on some of those fields below.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% block content %}
<div class="card shadow-lg border-0 rounded-lg mt-5">
    <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
    </div>
    <div class="card-body">
        <form action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
<!--            <div class="form-group">-->
<!--                <label class="small mb-1" for="inputEmailAddress">Имя пользователя</label>-->
<!--                <input class="form-control py-4" id="inputEmailAddress" type="email"-->
<!--                       placeholder="Введите имя пользователя"/>-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <label class="small mb-1" for="inputPassword">Пароль</label>-->
<!--                <input class="form-control py-4" id="inputPassword" type="password"-->
<!--                       placeholder="Введите пароль"/>-->
<!--            </div>-->
            <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                <a class="small" href="#">Забыли пароль?</a>
                <input class="btn btn-primary" type="submit" value="Авторизоваться">
            </div>
        </form>
    </div>
    <div class="card-footer text-center">
        <div class="small"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% block content %}
<div class="card shadow-lg border-0 rounded-lg mt-5">
    <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
    </div>
    <div class="card-body">
        <form>
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="small mb-1" for="inputFirstName">Имя</label>
                        <input class="form-control py-4" id="inputFirstName" type="text"
                               placeholder="Введите имя"/>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="small mb-1" for="inputLastName">Фамилия</label>
                        <input class="form-control py-4" id="inputLastName" type="text"
                               placeholder="Введите фамилию"/>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6">
                    <label class="small mb-1" for="inputUsername">Имя пользователя</label>
                    <input class="form-control py-4" id="inputUsername" type="text"
                           aria-describedby="usernameHelp"
                           placeholder="Введите имя пользователя"/>
                </div>
                <div class="col-md-6">
                    <label class="small mb-1" for="inputEmailAddress">Адрес электронной
                        почты</label>
                    <input class="form-control py-4" id="inputEmailAddress" type="email"
                           aria-describedby="emailHelp"
                           placeholder="Введите адрес эл. почты"/>
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="small mb-1" for="inputPassword">Пароль</label>
                        <input class="form-control py-4" id="inputPassword" type="password"
                               placeholder="Введите пароль"/>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="small mb-1" for="inputConfirmPassword">Подтверждение
                            пароля</label>
                        <input class="form-control py-4" id="inputConfirmPassword"
                               type="password" placeholder="Подтвердите пароль"/>
                    </div>
                </div>
            </div>
            <div class="form-group mt-4 mb-0">
                <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
            </div>
        </form>
    </div>
    <div class="card-footer text-center">
        <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
    </div>
</div>
{% endblock %}